name: coverage
on:
  - push
  - pull_request

jobs:
  steps:
    name: coverage
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
          pip install poetry
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: poetry run coverage xml
        