name: coverage
on:
  - push
  - pull_request

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: npm run coverage
        