name: "python-project-lvl2 checks"

on:
  - push
  - pull_request

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: publish code coverage to code-climate (duh)
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        poetry run coverage xml